"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useState} from "react";
import {LayoutDashboard,Search,Star,Building2,Bell,Sparkles,History,Settings,Shield,Menu,LogOut,ChartNoAxesCombined} from "lucide-react";
const links=[["/dashboard","Dashboard",LayoutDashboard],["/oportunidades","Oportunidades",Search],["/favoritos","Favoritos",Star],["/empresas","Empresas",Building2],["/alertas","Alertas",Bell],["/analises","Análises",Sparkles],["/notificacoes","Notificações",Bell],["/historico","Histórico",History],["/relatorios","Relatórios",ChartNoAxesCombined],["/configuracoes","Configurações",Settings]] as const;
export function Shell({name,admin,children}:{name:string;admin:boolean;children:React.ReactNode}){
 const path=usePathname(),[open,setOpen]=useState(false),[error,setError]=useState("");
 async function logout(){try{const r=await fetch("/api/auth/logout",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});if(!r.ok)throw new Error();location.href="/login";}catch{setError("Não foi possível sair. Tente novamente.");}}
 return <div className="shell"><a className="skip" href="#main">Ir para o conteúdo</a><aside className={open?"sidebar visible":"sidebar"}><Link href="/dashboard" className="brand"><span className="brand-symbol">P</span><span>PNCP<strong>Intelligence</strong></span></Link><div className="nav-label">ESPAÇO DE TRABALHO</div><nav aria-label="Navegação principal">{links.map(([href,label,Icon])=><Link key={href} href={href} onClick={()=>setOpen(false)} className={path.startsWith(href)?"nav-link active":"nav-link"}><Icon size={18}/>{label}</Link>)}{admin&&<Link href="/admin" className={path.startsWith("/admin")?"nav-link active":"nav-link"}><Shield size={18}/>Administração</Link>}</nav><div className="sidebar-foot"><span className="avatar">{name.slice(0,1)}</span><span>{name}<small>Conta autenticada</small></span><button className="icon-button" aria-label="Sair" onClick={logout}><LogOut size={18}/></button></div></aside><div className="main-wrap"><header className="topbar"><button className="mobile-toggle icon-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Abrir menu"><Menu/></button><span>Inteligência em contratações públicas</span><Link href="/notificacoes" aria-label="Notificações"><Bell size={20}/></Link></header><main id="main">{error&&<p role="alert" className="error">{error}</p>}{children}</main><footer>Dados públicos do PNCP · Confirme condições e atualizações na fonte oficial.</footer></div></div>;
}
